"use server";

import { refresh } from "next/cache";

import { createClient } from "@/lib/supabase/server";
import { readDraft, validateDraft, type DraftField } from "@/lib/stickers";

/**
 * Same shape as `PlaceResult` in `stickers.ts`, plus which field to point at.
 *
 * `field` is null when the failure belongs to no particular input — signed out,
 * or Postgres declining for a reason the form can't help with. The form still
 * prints the sentence; it just doesn't mark a box red.
 */
export type CreateResult =
  | { ok: true }
  | { ok: false; field: DraftField | null; message: string };

/** Postgres, not Supabase: `code` on a PostgrestError is the SQLSTATE. */
const UNIQUE_VIOLATION = "23505";
const FOREIGN_KEY_VIOLATION = "23503";
const INVALID_TEXT_REPRESENTATION = "22P02";

/**
 * Make a new sticker.
 *
 * Takes `FormData` rather than three arguments, which is what lets the form
 * call it as `<form action={…}>` — React serializes the fields, posts them, and
 * hands them here. There is no route to write, no fetch to call, and no JSON
 * to parse on either side.
 *
 * It re-validates. The browser already ran `validateDraft` on these same three
 * strings and refused to send anything that failed — but a Server Action is a
 * POST endpoint like any other, and the form in front of it is a convenience,
 * not a gate. Anyone can send this request without ever loading the page. The
 * check here is the one that counts; the one in the browser is there so a typo
 * doesn't cost a round trip.
 *
 * What's deliberately *not* checked: whether `lifeAreaId` is one of yours. The
 * row is written with your own `user_id`, and `activities` references
 * `(life_area_id, user_id)` as a pair — so an area belonging to someone else
 * has no row to point at and Postgres rejects the insert. Same reasoning as
 * `placeActivity`, and the same reason `lib/queries/` carries no `user_id`
 * filter: one answer to the question, in the place that can't be skipped.
 */
export async function createActivity(
  formData: FormData,
): Promise<CreateResult> {
  const check = validateDraft(readDraft(formData));
  if (!check.ok) {
    return { ok: false, field: check.field, message: check.message };
  }
  // The cleaned-up draft, not the raw fields — trimming happens once, inside
  // the validator, and what comes back out is what gets written.
  const { name, mark, lifeAreaId } = check.draft;

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return { ok: false, field: null, message: "You're signed out." };
  }

  const { error } = await supabase.from("activities").insert({
    user_id: user.id,
    life_area_id: lifeAreaId,
    name,
    mark,
  });

  if (error) {
    // Three of Postgres's refusals are things the person at the keyboard can
    // fix, so they get their own sentence and their own field. Everything else
    // is ours to fix and says so in one line.
    if (error.code === UNIQUE_VIOLATION) {
      return {
        ok: false,
        field: "name",
        message: `You already have a sticker called “${name}” in that area.`,
      };
    }
    if (
      error.code === FOREIGN_KEY_VIOLATION ||
      error.code === INVALID_TEXT_REPRESENTATION
    ) {
      return {
        ok: false,
        field: "lifeArea",
        message: "That life area isn't one of yours.",
      };
    }
    return {
      ok: false,
      field: null,
      message: "That sticker didn't save. Try again.",
    };
  }

  // The tray is rendered from `getStickerLibrary()` on the server, so this is
  // what makes the new sticker appear in it. `refresh()` re-runs the route and
  // ships the new RSC payload back inside this same response — the sticker and
  // the "ok" arrive together, one round trip, no follow-up fetch.
  //
  // Nothing optimistic here, unlike a drop: a new row's id is generated by the
  // database, and the tray keys on it. Inventing one would put a second source
  // of truth on screen for the length of a round trip, and the only thing it
  // would buy is a sticker appearing a beat sooner in a list you're not
  // looking at while the dialog is still open.
  refresh();
  return { ok: true };
}
