import {
  Accessibility,
  Activity,
  AlarmClock,
  Ambulance,
  Anchor,
  Angry,
  Annoyed,
  Aperture,
  Apple,
  Armchair,
  Atom,
  AudioLines,
  Award,
  Axe,
  Baby,
  Backpack,
  Balloon,
  Ban,
  Banana,
  Bandage,
  Banknote,
  Bath,
  Beaker,
  Bean,
  Bed,
  BedDouble,
  Beef,
  Beer,
  BeerOff,
  Bell,
  BicepsFlexed,
  Bike,
  Binary,
  Binoculars,
  Bird,
  Blender,
  Blocks,
  Bone,
  BoneFracture,
  Book,
  BookAudio,
  BookCheck,
  BookHeadphones,
  BookHeart,
  BookLock,
  BookMarked,
  BookOpen,
  BookOpenText,
  BookPlus,
  BookText,
  BookUser,
  Bookmark,
  BookmarkCheck,
  BoomBox,
  Bot,
  BottleWine,
  BowArrow,
  Boxes,
  Braces,
  Brain,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseMedical,
  Broccoli,
  Brush,
  BrushCleaning,
  Bubbles,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  Candy,
  CandyOff,
  Car,
  Carrot,
  Cat,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  CheckCheck,
  ChefHat,
  Cherry,
  Church,
  Cigarette,
  CigaretteOff,
  Citrus,
  Clapperboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  ClockAlert,
  Cloud,
  CloudMoon,
  CloudSun,
  Clover,
  CodeXml,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Crop,
  Cross,
  CupSoda,
  Database,
  Dices,
  Disc3,
  DiscAlbum,
  Dna,
  Dog,
  Donut,
  DoorOpen,
  DraftingCompass,
  Drama,
  Drill,
  Droplet,
  Droplets,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  Earth,
  Eclipse,
  Egg,
  EggFried,
  Eraser,
  Eye,
  EyeClosed,
  Factory,
  Feather,
  FerrisWheel,
  FileText,
  Files,
  Film,
  FingerprintPattern,
  Fish,
  Flag,
  Flame,
  FlameKindling,
  FlaskConical,
  Flower,
  Flower2,
  FolderOpen,
  Footprints,
  Frame,
  Frown,
  Gamepad2,
  Gauge,
  Gift,
  GlassWater,
  Glasses,
  Globe,
  Goal,
  GraduationCap,
  Grape,
  Guitar,
  Hamburger,
  Hammer,
  Hand,
  HandCoins,
  HandFist,
  HandHeart,
  HandHelping,
  Handshake,
  Haze,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPlus,
  HeartPulse,
  Highlighter,
  Hospital,
  Hourglass,
  House,
  IceCreamCone,
  Image as ImageIcon,
  Images,
  Inbox,
  Infinity,
  Kanban,
  Kayak,
  Keyboard,
  KeyboardMusic,
  Lamp,
  LampDesk,
  Landmark,
  Languages,
  Laptop,
  Laugh,
  Layers,
  Leaf,
  LeafyGreen,
  Lectern,
  Library,
  LibraryBig,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  ListTodo,
  Logs,
  Luggage,
  Mail,
  MailCheck,
  MailOpen,
  Map as MapIcon,
  MapPin,
  MapPinned,
  Mars,
  Martini,
  Medal,
  Megaphone,
  Meh,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Metronome,
  Mic,
  MicSignal,
  MicVocal,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  Monitor,
  Moon,
  MoonStar,
  Mosque,
  Motorbike,
  Mountain,
  MountainSnow,
  Mouse,
  Move,
  Music,
  Music4,
  Newspaper,
  Notebook,
  NotebookPen,
  NotebookTabs,
  NotebookText,
  NotepadText,
  Orbit,
  Origami,
  PaintBucket,
  Paintbrush,
  PaintbrushVertical,
  Palette,
  Paperclip,
  PartyPopper,
  PawPrint,
  Pen,
  PenLine,
  PenTool,
  Pencil,
  PencilLine,
  PencilRuler,
  Percent,
  PersonStanding,
  PhoneCall,
  Pi,
  Piano,
  Pickaxe,
  PiggyBank,
  Pill,
  PillBottle,
  Pipette,
  Pizza,
  Plane,
  PlaneTakeoff,
  Podium,
  Popcorn,
  Popsicle,
  Presentation,
  Printer,
  Projector,
  Puzzle,
  Quote,
  Rabbit,
  Radio,
  Rainbow,
  Receipt,
  ReceiptText,
  Recycle,
  Refrigerator,
  Repeat,
  Rocket,
  RockingChair,
  Rose,
  RotateCcwClock,
  Route,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  Scan,
  ScanFace,
  ScanHeart,
  ScanLine,
  School,
  Scissors,
  Scooter,
  Scroll,
  ScrollText,
  Search,
  Send,
  Shapes,
  Shell,
  ShieldCheck,
  ShieldPlus,
  Ship,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Shrimp,
  Shrub,
  Sigma,
  Signature,
  Signpost,
  Smartphone,
  Smile,
  Snail,
  Snowflake,
  SoapDispenserDroplet,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  SpellCheck,
  Spool,
  SportShoe,
  Sprout,
  Squirrel,
  Stamp,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  StretchHorizontal,
  Sun,
  SunMoon,
  Sunrise,
  Sunset,
  SwatchBook,
  Swords,
  Syringe,
  Tally5,
  Target,
  Telescope,
  Tent,
  TentTree,
  Terminal,
  TestTubes,
  Theater,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Ticket,
  Timer,
  TimerReset,
  Toilet,
  TowelRack,
  ToyBrick,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Turtle,
  Tv,
  Type,
  Umbrella,
  University,
  UserPlus,
  UserRoundCheck,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Variable,
  Vegan,
  VenetianMask,
  Venus,
  Video,
  Videotape,
  Volleyball,
  Volume,
  VolumeOff,
  Vote,
  Wallet,
  WalletCards,
  WandSparkles,
  Warehouse,
  WashingMachine,
  Watch,
  WavesHorizontal,
  WavesLadder,
  Waypoints,
  Weight,
  Wheat,
  Wind,
  Wine,
  WineOff,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import {
  Basketball,
  Carabiner,
  Golf,
  Lotus,
  Rowing,
  Ski,
  Surf,
  Tennis,
} from "./icons-custom.ts";

/**
 * The one place a sticker's picture is decided.
 *
 * A mark used to be exactly one grapheme — a letter or an emoji — and the
 * picture came from whichever font the reader happened to have. That is a lot
 * of drawing to hand to a font vendor: an emoji arrives with its own palette,
 * its own stroke weight and its own idea of how much of the em to fill, and it
 * looks different on macOS, Android and Windows. Thirty of them on the signed
 * out page read as thirty unrelated pictures rather than one set.
 *
 * So a mark now names an icon, and this file is the map from that name to the
 * component that draws it. One weight, one size rule, one colour, and the same
 * four hundred and thirty-two everywhere: the calendar, the tray, the day
 * modal, the picker and the login background all resolve through `iconFor`
 * rather than carrying a glyph of their own.
 *
 * **The emoji tabs are gone.** The picker offered all 1,914 of Unicode's emoji
 * behind this set for one release, as the escape hatch for a habit the set had
 * no picture for. The set is now large enough that the hatch was costing more
 * than it opened: an emoji chosen from it looked like nothing else in the app,
 * and a picker whose second tab is a wall of faces teaches that the first tab
 * is the short list rather than the whole vocabulary. Growing this file from
 * fifty-four to two hundred and sixteen is what made that trade payable, and
 * four hundred and thirty-two is what makes it comfortable.
 *
 * A mark can still be a single grapheme — see `validateDraft` in
 * `lib/stickers.ts` — and `StickerMark` still draws one. That path is now for
 * two things only: a typed letter, which is a legitimate mark and always was,
 * and the emoji already sitting in somebody's database, which keep working
 * exactly as they did. Nothing was migrated and nothing was lost; there is
 * simply no longer a way to pick a *new* emoji.
 *
 * Lucide rather than a second family, because `lucide-react` was already a
 * dependency and already draws every icon in the app's chrome. Two icon
 * families in one interface is the thing this file exists to prevent.
 *
 * Eight of the four hundred and thirty-two are not Lucide's. Lucide ships no
 * tennis racket, no basketball, no golf, ski, surf, rowing, climbing or yoga
 * pose, and those are habits people actually keep — so they are drawn by hand
 * in `lib/icons-custom.ts`, on Lucide's grid, with Lucide's own factory. They
 * are not an exception to the rule above; they are what keeps it true, because
 * the alternative was installing a second family for eight glyphs.
 */

/**
 * What a stored mark looks like when it names an icon: `icon:dumbbell`.
 *
 * The prefix is doing real work, not namespacing for its own sake. Without it,
 * "run" typed into the mark field would silently become a picture of footprints
 * — the field takes free text and always has. With it, an icon mark is
 * unmistakable in a psql dump, in a CSV export and in the one line of
 * `StickerMark` that has to decide which of the two things it is holding.
 */
export const ICON_PREFIX = "icon:";

/**
 * The stroke weight, and it is not a taste knob.
 *
 * Lucide draws into a 24-unit box and scales the stroke with it, so a weight of
 * 1.5 at a 16px icon is exactly 1 CSS pixel — one device pixel at 1x, two at
 * 2x, crisp on both. 1.75 was tried first, on the theory that a small icon
 * wants a heavier line; it lands at 1.17px, which no display can draw and both
 * resolve by blurring. It is also the weight the rest of the chrome already
 * uses, which is the other half of "one set".
 */
export const MARK_STROKE = 1.5;

/**
 * The size rule, as a class, and it is an `em` on purpose.
 *
 * A sticker circle already carries a `text-*` class that scales the mark inside
 * it — `text-[0.8rem]` on the calendar, up to `text-2xl` on the login page — so
 * an icon sized in `em` inherits every one of those without `StickerMark`
 * learning about any of them. One knob, already turned.
 *
 * 1.25 rather than 1, because the two things are measured differently: an emoji
 * glyph fills roughly its whole em, while a Lucide icon's ink fills about 83%
 * of its box. 1.25em of box is 1.04em of ink, which is the same picture the
 * emoji was drawing.
 */
export const MARK_ICON_SIZE = "size-[1.25em]";

/** One icon: what it is called, what finds it, and what draws it. */
export type MarkIcon = {
  /** The part after `icon:` — Lucide's own kebab-case name for the glyph. */
  id: string;
  /**
   * The word under the picture, and what a tooltip says.
   *
   * Usually Lucide's name, but not always: the glyph Lucide calls
   * `waves-ladder` is labelled "pool" here, and `check-check` is "done". The
   * name of a drawing and the name of a habit are different jobs, and this
   * field has the second one. Whatever the label is, the Lucide name is still
   * the id, so the two never drift.
   */
  label: string;
  /**
   * The rest of what someone might type looking for it, space separated.
   *
   * This is the whole reason the set is curated rather than "all 1,759 icons
   * Lucide ships". The package carries no keyword metadata — the tags live in
   * `lucide-static`, which is not installed — so a full-set picker could only
   * be searched by Lucide's own terse names, where "gym" finds nothing and
   * "run" finds nothing. Every icon below is hand-keyworded instead, and the
   * habits the app seeds are in here almost verbatim.
   */
  keywords: string;
  Icon: LucideIcon;
};

/**
 * One tab of the picker: fifty-four icons that belong to one another.
 *
 * `MarkPicker` draws nine columns by six rows and pages at fifty-four, so a
 * group is exactly one page — every tab fills its grid, no tab has a second
 * page, and the panel is the same height wherever you are. A fifty-fifth icon
 * in any group would put one icon alone on a page two. Add and remove in whole
 * rows of nine, and keep the groups equal.
 */
export type IconGroup = {
  /** Used as the Radix tab value, and derived from the label. */
  id: string;
  label: string;
  /**
   * The picture on the tab, because six words don't fit across a popover.
   *
   * It lives here rather than in `MarkPicker` because it is the same kind of
   * decision as everything else in this file — which glyph stands for a
   * category — and a tab whose icon is chosen a file away from the icons it
   * introduces is a tab that drifts. It is drawn from the same set at the same
   * weight, so the tab row and the grid under it match.
   */
  Tab: LucideIcon;
  icons: readonly MarkIcon[];
};

/**
 * Four hundred and thirty-two icons in eight groups of fifty-four.
 *
 * The groups are the life areas the app seeds, loosely — move, mind, reading,
 * work, make, home, health, people — but only loosely, because a set this size
 * is browsed rather than navigated and a tab is a place to start looking, not a
 * taxonomy. What a group actually guarantees is that the thing beside what you
 * found is plausibly the thing you meant.
 *
 * It was fifty-four in six groups of nine, on the theory that a set small
 * enough to see at once was friendlier than a wall. It was, right up until the
 * habit you wanted wasn't in it — and then the field silently became
 * letters-only, because the emoji tab was the only other answer and an emoji
 * doesn't look like the rest of the app. Growing it is what let the emoji tab
 * go, and the two groups added on the way out — health and care, read and learn
 * — are the two the first pass had nowhere to put. A doctor's appointment and a
 * chapter before bed are as much a tracked day as a gym session is.
 *
 * Every Lucide id here is Lucide's own kebab-case name, checked against the
 * installed package rather than guessed: a few names exist only as deprecated
 * aliases and will not resolve. If you add one, confirm it appears in
 * `node_modules/lucide-react/dist/esm/dynamicIconImports.mjs` first. The eight
 * ids that are not Lucide's — tennis, basketball, golf, ski, surf, rowing,
 * carabiner, lotus — are named by the same rule in `lib/icons-custom.ts`, and
 * are the only ids in this file that manifest will not know.
 */
export const ICON_GROUPS: readonly IconGroup[] = [
  {
    id: "move",
    label: "Move",
    Tab: Activity,
    icons: [
      {
        id: "dumbbell",
        label: "dumbbell",
        keywords: "gym weights strength lift workout",
        Icon: Dumbbell,
      },
      {
        id: "biceps-flexed",
        label: "strength",
        keywords: "gym muscle lift strong",
        Icon: BicepsFlexed,
      },
      {
        id: "weight",
        label: "weight",
        keywords: "kettlebell lift scale",
        Icon: Weight,
      },
      {
        id: "footprints",
        label: "footprints",
        keywords: "run running jog steps walk",
        Icon: Footprints,
      },
      {
        id: "sport-shoe",
        label: "trainers",
        keywords: "run running shoes jog",
        Icon: SportShoe,
      },
      {
        id: "mountain",
        label: "mountain",
        keywords: "hike hiking outdoors trail",
        Icon: Mountain,
      },
      {
        id: "mountain-snow",
        label: "summit",
        keywords: "peak alpine climb",
        Icon: MountainSnow,
      },
      {
        id: "bike",
        label: "bike",
        keywords: "ride cycling bicycle spin",
        Icon: Bike,
      },
      {
        id: "motorbike",
        label: "motorbike",
        keywords: "ride motorcycle",
        Icon: Motorbike,
      },
      {
        id: "scooter",
        label: "scooter",
        keywords: "ride kick commute",
        Icon: Scooter,
      },
      {
        id: "waves-ladder",
        label: "pool",
        keywords: "swim swimming laps water",
        Icon: WavesLadder,
      },
      {
        id: "waves-horizontal",
        label: "open water",
        keywords: "swim sea wild swimming",
        Icon: WavesHorizontal,
      },
      {
        id: "tennis",
        label: "tennis",
        keywords: "racket racquet padel squash badminton",
        Icon: Tennis,
      },
      {
        id: "basketball",
        label: "basketball",
        keywords: "hoops ball court shoot",
        Icon: Basketball,
      },
      {
        id: "golf",
        label: "golf",
        keywords: "course putt driving range",
        Icon: Golf,
      },
      {
        id: "ski",
        label: "ski",
        keywords: "skiing snow slopes winter",
        Icon: Ski,
      },
      {
        id: "surf",
        label: "surf",
        keywords: "surfing waves board sea",
        Icon: Surf,
      },
      {
        id: "rowing",
        label: "rowing",
        keywords: "row erg scull boat",
        Icon: Rowing,
      },
      {
        id: "carabiner",
        label: "climbing",
        keywords: "climb bouldering crag rope",
        Icon: Carabiner,
      },
      {
        id: "lotus",
        label: "yoga",
        keywords: "meditate pose stretch flow pilates",
        Icon: Lotus,
      },
      {
        id: "volleyball",
        label: "volleyball",
        keywords: "sport team ball play",
        Icon: Volleyball,
      },
      {
        id: "goal",
        label: "football",
        keywords: "soccer sport net pitch",
        Icon: Goal,
      },
      {
        id: "kayak",
        label: "kayak",
        keywords: "paddle canoe river water",
        Icon: Kayak,
      },
      {
        id: "sailboat",
        label: "sailing",
        keywords: "boat dinghy water",
        Icon: Sailboat,
      },
      {
        id: "bow-arrow",
        label: "archery",
        keywords: "bow arrow target range",
        Icon: BowArrow,
      },
      {
        id: "swords",
        label: "fencing",
        keywords: "sword spar martial arts",
        Icon: Swords,
      },
      {
        id: "hand-fist",
        label: "boxing",
        keywords: "punch spar martial arts",
        Icon: HandFist,
      },
      {
        id: "person-standing",
        label: "person",
        keywords: "posture stand balance",
        Icon: PersonStanding,
      },
      {
        id: "accessibility",
        label: "accessibility",
        keywords: "mobility adaptive move body",
        Icon: Accessibility,
      },
      {
        id: "move",
        label: "move",
        keywords: "movement mobility flexibility",
        Icon: Move,
      },
      {
        id: "stretch-horizontal",
        label: "stretch",
        keywords: "mobility warm up flexibility",
        Icon: StretchHorizontal,
      },
      {
        id: "timer",
        label: "timer",
        keywords: "time interval stopwatch minutes",
        Icon: Timer,
      },
      {
        id: "timer-reset",
        label: "interval",
        keywords: "lap repeat reset",
        Icon: TimerReset,
      },
      {
        id: "hourglass",
        label: "hourglass",
        keywords: "duration wait patience",
        Icon: Hourglass,
      },
      {
        id: "gauge",
        label: "gauge",
        keywords: "pace speed effort intensity",
        Icon: Gauge,
      },
      {
        id: "trending-up",
        label: "trend",
        keywords: "progress improve gains",
        Icon: TrendingUp,
      },
      {
        id: "repeat",
        label: "repeat",
        keywords: "reps sets routine again",
        Icon: Repeat,
      },
      {
        id: "flame",
        label: "flame",
        keywords: "streak burn calories intensity",
        Icon: Flame,
      },
      {
        id: "zap",
        label: "zap",
        keywords: "energy burst hiit",
        Icon: Zap,
      },
      {
        id: "rocket",
        label: "rocket",
        keywords: "push effort launch power",
        Icon: Rocket,
      },
      {
        id: "target",
        label: "target",
        keywords: "goal aim focus bullseye",
        Icon: Target,
      },
      {
        id: "trophy",
        label: "trophy",
        keywords: "win goal streak achievement",
        Icon: Trophy,
      },
      {
        id: "medal",
        label: "medal",
        keywords: "race win award finish",
        Icon: Medal,
      },
      {
        id: "award",
        label: "award",
        keywords: "badge prize recognition",
        Icon: Award,
      },
      {
        id: "route",
        label: "route",
        keywords: "distance course path miles",
        Icon: Route,
      },
      {
        id: "milestone",
        label: "milestone",
        keywords: "marker progress distance",
        Icon: Milestone,
      },
      {
        id: "waypoints",
        label: "waypoints",
        keywords: "legs intervals route",
        Icon: Waypoints,
      },
      {
        id: "compass",
        label: "compass",
        keywords: "orienteering direction explore",
        Icon: Compass,
      },
      {
        id: "tent",
        label: "tent",
        keywords: "camp camping overnight",
        Icon: Tent,
      },
      {
        id: "tent-tree",
        label: "campsite",
        keywords: "camping wild outdoors",
        Icon: TentTree,
      },
      {
        id: "backpack",
        label: "backpack",
        keywords: "hike trek carry gear",
        Icon: Backpack,
      },
      {
        id: "snowflake",
        label: "snowflake",
        keywords: "snow winter cold plunge",
        Icon: Snowflake,
      },
      {
        id: "bone",
        label: "bone",
        keywords: "joints mobility physio",
        Icon: Bone,
      },
      {
        id: "activity",
        label: "activity",
        keywords: "exercise session move",
        Icon: Activity,
      },
    ],
  },
  {
    id: "mind-and-rest",
    label: "Mind and rest",
    Tab: Sparkles,
    icons: [
      {
        id: "sparkles",
        label: "sparkles",
        keywords: "meditation meditate calm quiet",
        Icon: Sparkles,
      },
      {
        id: "sparkle",
        label: "spark",
        keywords: "small joy notice calm",
        Icon: Sparkle,
      },
      {
        id: "wand-sparkles",
        label: "ritual",
        keywords: "practice intention magic",
        Icon: WandSparkles,
      },
      {
        id: "brain",
        label: "brain",
        keywords: "mind think reflect",
        Icon: Brain,
      },
      {
        id: "wind",
        label: "wind",
        keywords: "breathe breathing breath calm",
        Icon: Wind,
      },
      {
        id: "moon",
        label: "moon",
        keywords: "night wind down evening",
        Icon: Moon,
      },
      {
        id: "moon-star",
        label: "night sky",
        keywords: "sleep bedtime dream",
        Icon: MoonStar,
      },
      {
        id: "sunrise",
        label: "sunrise",
        keywords: "early morning wake dawn",
        Icon: Sunrise,
      },
      {
        id: "sun-moon",
        label: "rhythm",
        keywords: "day night balance routine",
        Icon: SunMoon,
      },
      {
        id: "bed",
        label: "bed",
        keywords: "sleep early night rest",
        Icon: Bed,
      },
      {
        id: "bed-double",
        label: "bedtime",
        keywords: "sleep rest night",
        Icon: BedDouble,
      },
      {
        id: "armchair",
        label: "armchair",
        keywords: "rest day relax sit break",
        Icon: Armchair,
      },
      {
        id: "sofa",
        label: "sofa",
        keywords: "lounge relax evening",
        Icon: Sofa,
      },
      {
        id: "rocking-chair",
        label: "rocking chair",
        keywords: "slow calm sit",
        Icon: RockingChair,
      },
      {
        id: "bath",
        label: "bath",
        keywords: "soak relax unwind wash",
        Icon: Bath,
      },
      {
        id: "shower-head",
        label: "shower",
        keywords: "wash morning routine cold",
        Icon: ShowerHead,
      },
      {
        id: "cloud",
        label: "cloud",
        keywords: "daydream drift calm",
        Icon: Cloud,
      },
      {
        id: "cloud-moon",
        label: "dusk",
        keywords: "evening calm night",
        Icon: CloudMoon,
      },
      {
        id: "rainbow",
        label: "rainbow",
        keywords: "hope mood bright",
        Icon: Rainbow,
      },
      {
        id: "star",
        label: "star",
        keywords: "wish gratitude highlight",
        Icon: Star,
      },
      {
        id: "church",
        label: "church",
        keywords: "prayer pray faith worship service",
        Icon: Church,
      },
      {
        id: "mosque",
        label: "mosque",
        keywords: "prayer pray faith worship",
        Icon: Mosque,
      },
      {
        id: "cross",
        label: "cross",
        keywords: "faith prayer chapel",
        Icon: Cross,
      },
      {
        id: "infinity",
        label: "infinity",
        keywords: "ongoing practice forever",
        Icon: Infinity,
      },
      {
        id: "orbit",
        label: "orbit",
        keywords: "cycle rhythm return",
        Icon: Orbit,
      },
      {
        id: "eclipse",
        label: "eclipse",
        keywords: "phase change quiet",
        Icon: Eclipse,
      },
      {
        id: "atom",
        label: "atom",
        keywords: "focus centre still",
        Icon: Atom,
      },
      {
        id: "flower-2",
        label: "blossom",
        keywords: "bloom calm nature",
        Icon: Flower2,
      },
      {
        id: "shell",
        label: "shell",
        keywords: "beach slow calm",
        Icon: Shell,
      },
      {
        id: "snail",
        label: "slow",
        keywords: "pace patience gentle",
        Icon: Snail,
      },
      {
        id: "turtle",
        label: "turtle",
        keywords: "steady slow pace",
        Icon: Turtle,
      },
      {
        id: "ear",
        label: "ear",
        keywords: "listen hearing attention",
        Icon: Ear,
      },
      {
        id: "eye",
        label: "eye",
        keywords: "notice look attention",
        Icon: Eye,
      },
      {
        id: "eye-closed",
        label: "eyes closed",
        keywords: "rest screen break",
        Icon: EyeClosed,
      },
      {
        id: "glasses",
        label: "glasses",
        keywords: "read screen eyes rest",
        Icon: Glasses,
      },
      {
        id: "headphones",
        label: "headphones",
        keywords: "music podcast listen audio",
        Icon: Headphones,
      },
      {
        id: "audio-lines",
        label: "audio",
        keywords: "podcast listen sound voice",
        Icon: AudioLines,
      },
      {
        id: "mic-signal",
        label: "podcast",
        keywords: "listen episode show",
        Icon: MicSignal,
      },
      {
        id: "puzzle",
        label: "puzzle",
        keywords: "crossword think play",
        Icon: Puzzle,
      },
      {
        id: "blocks",
        label: "blocks",
        keywords: "build play focus",
        Icon: Blocks,
      },
      {
        id: "dices",
        label: "dice",
        keywords: "board game play",
        Icon: Dices,
      },
      {
        id: "gamepad-2",
        label: "games",
        keywords: "console gaming play",
        Icon: Gamepad2,
      },
      {
        id: "tv",
        label: "tv",
        keywords: "watch something show evening",
        Icon: Tv,
      },
      {
        id: "popcorn",
        label: "popcorn",
        keywords: "film night treat watch",
        Icon: Popcorn,
      },
      {
        id: "quote",
        label: "quote",
        keywords: "reflection words journal",
        Icon: Quote,
      },
      {
        id: "lightbulb",
        label: "lightbulb",
        keywords: "idea insight notice",
        Icon: Lightbulb,
      },
      {
        id: "feather",
        label: "feather",
        keywords: "light gentle ease",
        Icon: Feather,
      },
      {
        id: "flame-kindling",
        label: "fire",
        keywords: "warmth evening calm",
        Icon: FlameKindling,
      },
      {
        id: "lamp-desk",
        label: "desk lamp",
        keywords: "evening light calm",
        Icon: LampDesk,
      },
      {
        id: "clover",
        label: "luck",
        keywords: "gratitude notice charm",
        Icon: Clover,
      },
      {
        id: "volume",
        label: "quiet",
        keywords: "sound low calm",
        Icon: Volume,
      },
      {
        id: "volume-off",
        label: "silence",
        keywords: "mute quiet still",
        Icon: VolumeOff,
      },
      {
        id: "haze",
        label: "haze",
        keywords: "mist soft calm",
        Icon: Haze,
      },
      {
        id: "anchor",
        label: "steady",
        keywords: "ground grounding anchor",
        Icon: Anchor,
      },
    ],
  },
  {
    id: "read-and-learn",
    label: "Read and learn",
    Tab: BookOpen,
    icons: [
      {
        id: "book-open",
        label: "book",
        keywords: "read reading pages",
        Icon: BookOpen,
      },
      {
        id: "book",
        label: "closed book",
        keywords: "read finish chapter",
        Icon: Book,
      },
      {
        id: "book-marked",
        label: "bookmarked book",
        keywords: "study reference reading",
        Icon: BookMarked,
      },
      {
        id: "book-heart",
        label: "loved book",
        keywords: "favourite reading comfort",
        Icon: BookHeart,
      },
      {
        id: "book-open-text",
        label: "reading",
        keywords: "pages text chapter",
        Icon: BookOpenText,
      },
      {
        id: "book-check",
        label: "finished",
        keywords: "read done book",
        Icon: BookCheck,
      },
      {
        id: "book-audio",
        label: "audiobook",
        keywords: "listen read audio",
        Icon: BookAudio,
      },
      {
        id: "book-headphones",
        label: "listening",
        keywords: "audiobook read listen",
        Icon: BookHeadphones,
      },
      {
        id: "book-text",
        label: "textbook",
        keywords: "study read notes",
        Icon: BookText,
      },
      {
        id: "book-user",
        label: "memoir",
        keywords: "biography read life",
        Icon: BookUser,
      },
      {
        id: "book-lock",
        label: "diary",
        keywords: "private journal write",
        Icon: BookLock,
      },
      {
        id: "book-plus",
        label: "to read",
        keywords: "list pile books",
        Icon: BookPlus,
      },
      {
        id: "library",
        label: "library",
        keywords: "books study reading",
        Icon: Library,
      },
      {
        id: "library-big",
        label: "shelves",
        keywords: "books collection reading",
        Icon: LibraryBig,
      },
      {
        id: "bookmark",
        label: "bookmark",
        keywords: "save reading place",
        Icon: Bookmark,
      },
      {
        id: "bookmark-check",
        label: "read it",
        keywords: "saved finished bookmark",
        Icon: BookmarkCheck,
      },
      {
        id: "newspaper",
        label: "newspaper",
        keywords: "news read morning paper",
        Icon: Newspaper,
      },
      {
        id: "scroll-text",
        label: "scroll",
        keywords: "read long text notes",
        Icon: ScrollText,
      },
      {
        id: "notebook",
        label: "journal",
        keywords: "notes diary pages",
        Icon: Notebook,
      },
      {
        id: "notebook-pen",
        label: "notebook",
        keywords: "journal journaling write it down diary",
        Icon: NotebookPen,
      },
      {
        id: "notebook-text",
        label: "notes",
        keywords: "journal write pages",
        Icon: NotebookText,
      },
      {
        id: "notebook-tabs",
        label: "sections",
        keywords: "notes journal organise",
        Icon: NotebookTabs,
      },
      {
        id: "pen-line",
        label: "pen",
        keywords: "write note draft",
        Icon: PenLine,
      },
      {
        id: "pen",
        label: "write",
        keywords: "journal note ink",
        Icon: Pen,
      },
      {
        id: "highlighter",
        label: "highlighter",
        keywords: "study notes mark revise",
        Icon: Highlighter,
      },
      {
        id: "graduation-cap",
        label: "graduation",
        keywords: "study course learn class",
        Icon: GraduationCap,
      },
      {
        id: "school",
        label: "school",
        keywords: "study class lesson",
        Icon: School,
      },
      {
        id: "university",
        label: "university",
        keywords: "degree study course",
        Icon: University,
      },
      {
        id: "lectern",
        label: "lecture",
        keywords: "talk class study",
        Icon: Lectern,
      },
      {
        id: "languages",
        label: "languages",
        keywords: "learn language practice",
        Icon: Languages,
      },
      {
        id: "speech",
        label: "speaking",
        keywords: "language practice talk",
        Icon: Speech,
      },
      {
        id: "spell-check",
        label: "spelling",
        keywords: "writing words check",
        Icon: SpellCheck,
      },
      {
        id: "sigma",
        label: "maths",
        keywords: "sum numbers study",
        Icon: Sigma,
      },
      {
        id: "pi",
        label: "numbers",
        keywords: "maths formula study",
        Icon: Pi,
      },
      {
        id: "variable",
        label: "algebra",
        keywords: "maths formula study",
        Icon: Variable,
      },
      {
        id: "braces",
        label: "code",
        keywords: "programming dev practice",
        Icon: Braces,
      },
      {
        id: "code-xml",
        label: "coding",
        keywords: "programming build dev",
        Icon: CodeXml,
      },
      {
        id: "terminal",
        label: "terminal",
        keywords: "code shell dev",
        Icon: Terminal,
      },
      {
        id: "binary",
        label: "binary",
        keywords: "code data dev",
        Icon: Binary,
      },
      {
        id: "cpu",
        label: "cpu",
        keywords: "computing tech build",
        Icon: Cpu,
      },
      {
        id: "bot",
        label: "bot",
        keywords: "ai assistant chat",
        Icon: Bot,
      },
      {
        id: "laptop",
        label: "laptop",
        keywords: "work computer desk screen",
        Icon: Laptop,
      },
      {
        id: "monitor",
        label: "monitor",
        keywords: "screen desk computer",
        Icon: Monitor,
      },
      {
        id: "keyboard",
        label: "keyboard",
        keywords: "typing type practice",
        Icon: Keyboard,
      },
      {
        id: "mouse",
        label: "mouse",
        keywords: "computer input desk",
        Icon: Mouse,
      },
      {
        id: "smartphone",
        label: "phone",
        keywords: "screen time apps",
        Icon: Smartphone,
      },
      {
        id: "database",
        label: "database",
        keywords: "data records study",
        Icon: Database,
      },
      {
        id: "podium",
        label: "talk",
        keywords: "speech present class",
        Icon: Podium,
      },
      {
        id: "scroll",
        label: "manuscript",
        keywords: "read old text",
        Icon: Scroll,
      },
      {
        id: "flag",
        label: "flag",
        keywords: "milestone mark goal",
        Icon: Flag,
      },
      {
        id: "earth",
        label: "geography",
        keywords: "world atlas maps learn",
        Icon: Earth,
      },
      {
        id: "rotate-ccw-clock",
        label: "revision",
        keywords: "review recall repeat",
        Icon: RotateCcwClock,
      },
      {
        id: "tally-5",
        label: "tally",
        keywords: "count track record",
        Icon: Tally5,
      },
      {
        id: "search",
        label: "look up",
        keywords: "research find learn",
        Icon: Search,
      },
    ],
  },
  {
    id: "work-and-money",
    label: "Work and money",
    Tab: Briefcase,
    icons: [
      {
        id: "briefcase",
        label: "briefcase",
        keywords: "work job office",
        Icon: Briefcase,
      },
      {
        id: "briefcase-business",
        label: "business",
        keywords: "work company job",
        Icon: BriefcaseBusiness,
      },
      {
        id: "building-2",
        label: "office",
        keywords: "work commute building",
        Icon: Building2,
      },
      {
        id: "building",
        label: "building",
        keywords: "office work block",
        Icon: Building,
      },
      {
        id: "factory",
        label: "factory",
        keywords: "work shift industry",
        Icon: Factory,
      },
      {
        id: "warehouse",
        label: "warehouse",
        keywords: "work stock storage",
        Icon: Warehouse,
      },
      {
        id: "store",
        label: "shop",
        keywords: "business retail open",
        Icon: Store,
      },
      {
        id: "inbox",
        label: "inbox",
        keywords: "email inbox zero triage",
        Icon: Inbox,
      },
      {
        id: "mail",
        label: "mail",
        keywords: "email write a letter post",
        Icon: Mail,
      },
      {
        id: "mail-open",
        label: "opened mail",
        keywords: "read email reply",
        Icon: MailOpen,
      },
      {
        id: "mail-check",
        label: "email done",
        keywords: "replied inbox zero",
        Icon: MailCheck,
      },
      {
        id: "send",
        label: "send",
        keywords: "email reply message",
        Icon: Send,
      },
      {
        id: "check-check",
        label: "done",
        keywords: "complete finished todo",
        Icon: CheckCheck,
      },
      {
        id: "list-todo",
        label: "to do",
        keywords: "tasks list plan",
        Icon: ListTodo,
      },
      {
        id: "list-checks",
        label: "checklist",
        keywords: "tasks done review",
        Icon: ListChecks,
      },
      {
        id: "logs",
        label: "log",
        keywords: "track record notes",
        Icon: Logs,
      },
      {
        id: "clipboard-list",
        label: "clipboard",
        keywords: "plan tasks agenda",
        Icon: ClipboardList,
      },
      {
        id: "clipboard-check",
        label: "clipboard done",
        keywords: "review complete audit",
        Icon: ClipboardCheck,
      },
      {
        id: "notepad-text",
        label: "notepad",
        keywords: "notes plan jot",
        Icon: NotepadText,
      },
      {
        id: "sticky-note",
        label: "sticky note",
        keywords: "reminder note quick",
        Icon: StickyNote,
      },
      {
        id: "kanban",
        label: "board",
        keywords: "kanban tasks sprint",
        Icon: Kanban,
      },
      {
        id: "workflow",
        label: "workflow",
        keywords: "process steps pipeline",
        Icon: Workflow,
      },
      {
        id: "calendar",
        label: "calendar",
        keywords: "plan schedule date",
        Icon: Calendar,
      },
      {
        id: "calendar-check",
        label: "booked",
        keywords: "schedule confirm appointment",
        Icon: CalendarCheck,
      },
      {
        id: "calendar-days",
        label: "month",
        keywords: "plan schedule weeks",
        Icon: CalendarDays,
      },
      {
        id: "calendar-clock",
        label: "deadline",
        keywords: "due schedule time",
        Icon: CalendarClock,
      },
      {
        id: "alarm-clock",
        label: "alarm",
        keywords: "wake early morning",
        Icon: AlarmClock,
      },
      {
        id: "clock",
        label: "clock",
        keywords: "time hours track",
        Icon: Clock,
      },
      {
        id: "clock-alert",
        label: "overdue",
        keywords: "late deadline due",
        Icon: ClockAlert,
      },
      {
        id: "folder-open",
        label: "folder",
        keywords: "files admin organise",
        Icon: FolderOpen,
      },
      {
        id: "file-text",
        label: "document",
        keywords: "write doc report admin",
        Icon: FileText,
      },
      {
        id: "files",
        label: "files",
        keywords: "paperwork admin sort",
        Icon: Files,
      },
      {
        id: "paperclip",
        label: "attachment",
        keywords: "files admin attach",
        Icon: Paperclip,
      },
      {
        id: "printer",
        label: "print",
        keywords: "paperwork admin office",
        Icon: Printer,
      },
      {
        id: "presentation",
        label: "presentation",
        keywords: "slides talk meeting",
        Icon: Presentation,
      },
      {
        id: "projector",
        label: "projector",
        keywords: "present slides meeting",
        Icon: Projector,
      },
      {
        id: "chart-line",
        label: "line chart",
        keywords: "progress metrics review",
        Icon: ChartLine,
      },
      {
        id: "chart-bar",
        label: "bar chart",
        keywords: "numbers report data",
        Icon: ChartBar,
      },
      {
        id: "chart-pie",
        label: "pie chart",
        keywords: "budget split report",
        Icon: ChartPie,
      },
      {
        id: "chart-column",
        label: "columns",
        keywords: "report data metrics",
        Icon: ChartColumn,
      },
      {
        id: "coins",
        label: "coins",
        keywords: "money save budget",
        Icon: Coins,
      },
      {
        id: "banknote",
        label: "banknote",
        keywords: "money cash pay income",
        Icon: Banknote,
      },
      {
        id: "piggy-bank",
        label: "piggy bank",
        keywords: "save savings budget",
        Icon: PiggyBank,
      },
      {
        id: "wallet",
        label: "wallet",
        keywords: "spend budget money",
        Icon: Wallet,
      },
      {
        id: "wallet-cards",
        label: "cards",
        keywords: "spend budget accounts",
        Icon: WalletCards,
      },
      {
        id: "credit-card",
        label: "card",
        keywords: "pay spend bills",
        Icon: CreditCard,
      },
      {
        id: "receipt",
        label: "receipt",
        keywords: "expenses track spending",
        Icon: Receipt,
      },
      {
        id: "receipt-text",
        label: "invoice",
        keywords: "bill expenses admin",
        Icon: ReceiptText,
      },
      {
        id: "calculator",
        label: "calculator",
        keywords: "budget numbers accounts",
        Icon: Calculator,
      },
      {
        id: "landmark",
        label: "bank",
        keywords: "finance accounts institution",
        Icon: Landmark,
      },
      {
        id: "hand-coins",
        label: "payday",
        keywords: "income earn money",
        Icon: HandCoins,
      },
      {
        id: "megaphone",
        label: "megaphone",
        keywords: "announce marketing outreach",
        Icon: Megaphone,
      },
      {
        id: "bell",
        label: "bell",
        keywords: "reminder notification alert",
        Icon: Bell,
      },
      {
        id: "signature",
        label: "signature",
        keywords: "sign admin paperwork",
        Icon: Signature,
      },
    ],
  },
  {
    id: "make",
    label: "Make",
    Tab: Palette,
    icons: [
      {
        id: "palette",
        label: "palette",
        keywords: "paint art draw make",
        Icon: Palette,
      },
      {
        id: "paintbrush",
        label: "paintbrush",
        keywords: "paint art brush",
        Icon: Paintbrush,
      },
      {
        id: "paintbrush-vertical",
        label: "flat brush",
        keywords: "paint art strokes",
        Icon: PaintbrushVertical,
      },
      {
        id: "paint-bucket",
        label: "paint",
        keywords: "fill colour art",
        Icon: PaintBucket,
      },
      {
        id: "brush",
        label: "brush",
        keywords: "paint strokes art",
        Icon: Brush,
      },
      {
        id: "swatch-book",
        label: "swatches",
        keywords: "colour palette design",
        Icon: SwatchBook,
      },
      {
        id: "pipette",
        label: "colour picker",
        keywords: "swatch sample design",
        Icon: Pipette,
      },
      {
        id: "pencil",
        label: "pencil",
        keywords: "draw sketch write",
        Icon: Pencil,
      },
      {
        id: "pencil-line",
        label: "sketch",
        keywords: "draw doodle line",
        Icon: PencilLine,
      },
      {
        id: "eraser",
        label: "eraser",
        keywords: "sketch draft edit",
        Icon: Eraser,
      },
      {
        id: "pencil-ruler",
        label: "design",
        keywords: "draft plan sketch",
        Icon: PencilRuler,
      },
      {
        id: "ruler",
        label: "ruler",
        keywords: "measure plan draft",
        Icon: Ruler,
      },
      {
        id: "drafting-compass",
        label: "drafting",
        keywords: "technical draw plan",
        Icon: DraftingCompass,
      },
      {
        id: "pen-tool",
        label: "pen tool",
        keywords: "vector illustrate design",
        Icon: PenTool,
      },
      {
        id: "shapes",
        label: "shapes",
        keywords: "design geometry make",
        Icon: Shapes,
      },
      {
        id: "layers",
        label: "layers",
        keywords: "design edit stack",
        Icon: Layers,
      },
      {
        id: "frame",
        label: "frame",
        keywords: "photo art hang picture",
        Icon: Frame,
      },
      {
        id: "crop",
        label: "crop",
        keywords: "photo edit frame",
        Icon: Crop,
      },
      {
        id: "image",
        label: "image",
        keywords: "photo picture edit",
        Icon: ImageIcon,
      },
      {
        id: "images",
        label: "photos",
        keywords: "album gallery pictures",
        Icon: Images,
      },
      {
        id: "camera",
        label: "camera",
        keywords: "photo photography take a photo",
        Icon: Camera,
      },
      {
        id: "aperture",
        label: "aperture",
        keywords: "lens shoot photography",
        Icon: Aperture,
      },
      {
        id: "film",
        label: "film",
        keywords: "movie cinema watch",
        Icon: Film,
      },
      {
        id: "clapperboard",
        label: "clapperboard",
        keywords: "film video shoot edit",
        Icon: Clapperboard,
      },
      {
        id: "videotape",
        label: "tape",
        keywords: "record video archive",
        Icon: Videotape,
      },
      {
        id: "disc-3",
        label: "record",
        keywords: "vinyl album listen",
        Icon: Disc3,
      },
      {
        id: "disc-album",
        label: "album",
        keywords: "record vinyl listen",
        Icon: DiscAlbum,
      },
      {
        id: "music",
        label: "music",
        keywords: "song play listen",
        Icon: Music,
      },
      {
        id: "music-4",
        label: "sheet music",
        keywords: "compose practice song",
        Icon: Music4,
      },
      {
        id: "guitar",
        label: "guitar",
        keywords: "practice play strings band",
        Icon: Guitar,
      },
      {
        id: "piano",
        label: "piano",
        keywords: "practice play keys scales",
        Icon: Piano,
      },
      {
        id: "drum",
        label: "drum",
        keywords: "practice play rhythm",
        Icon: Drum,
      },
      {
        id: "keyboard-music",
        label: "keys",
        keywords: "practice midi play",
        Icon: KeyboardMusic,
      },
      {
        id: "metronome",
        label: "metronome",
        keywords: "practice tempo time",
        Icon: Metronome,
      },
      {
        id: "mic",
        label: "mic",
        keywords: "record voice podcast",
        Icon: Mic,
      },
      {
        id: "mic-vocal",
        label: "sing",
        keywords: "singing vocals karaoke choir",
        Icon: MicVocal,
      },
      {
        id: "radio",
        label: "radio",
        keywords: "listen station broadcast",
        Icon: Radio,
      },
      {
        id: "speaker",
        label: "speaker",
        keywords: "music listen sound",
        Icon: Speaker,
      },
      {
        id: "boom-box",
        label: "stereo",
        keywords: "music listen play",
        Icon: BoomBox,
      },
      {
        id: "theater",
        label: "theatre",
        keywords: "play show stage acting",
        Icon: Theater,
      },
      {
        id: "drama",
        label: "drama",
        keywords: "acting perform theatre",
        Icon: Drama,
      },
      {
        id: "venetian-mask",
        label: "mask",
        keywords: "drama costume perform",
        Icon: VenetianMask,
      },
      {
        id: "scissors",
        label: "scissors",
        keywords: "craft cut paper",
        Icon: Scissors,
      },
      {
        id: "origami",
        label: "origami",
        keywords: "craft paper fold make",
        Icon: Origami,
      },
      {
        id: "spool",
        label: "thread",
        keywords: "sew sewing knit craft",
        Icon: Spool,
      },
      {
        id: "shirt",
        label: "shirt",
        keywords: "sew clothes style",
        Icon: Shirt,
      },
      {
        id: "hammer",
        label: "hammer",
        keywords: "diy build repair",
        Icon: Hammer,
      },
      {
        id: "wrench",
        label: "wrench",
        keywords: "fix repair maintenance",
        Icon: Wrench,
      },
      {
        id: "drill",
        label: "drill",
        keywords: "diy build repair",
        Icon: Drill,
      },
      {
        id: "axe",
        label: "axe",
        keywords: "wood chop craft",
        Icon: Axe,
      },
      {
        id: "pickaxe",
        label: "pickaxe",
        keywords: "dig build craft",
        Icon: Pickaxe,
      },
      {
        id: "toy-brick",
        label: "bricks",
        keywords: "build make play",
        Icon: ToyBrick,
      },
      {
        id: "stamp",
        label: "stamp",
        keywords: "craft print make",
        Icon: Stamp,
      },
      {
        id: "type",
        label: "type",
        keywords: "typography writing words",
        Icon: Type,
      },
    ],
  },
  {
    id: "home-and-food",
    label: "Home and food",
    Tab: CookingPot,
    icons: [
      {
        id: "cooking-pot",
        label: "pot",
        keywords: "cook cooking dinner meal",
        Icon: CookingPot,
      },
      {
        id: "chef-hat",
        label: "chef",
        keywords: "cook recipe kitchen",
        Icon: ChefHat,
      },
      {
        id: "utensils",
        label: "utensils",
        keywords: "eat meal dinner food",
        Icon: Utensils,
      },
      {
        id: "utensils-crossed",
        label: "dining",
        keywords: "eat out restaurant meal",
        Icon: UtensilsCrossed,
      },
      {
        id: "blender",
        label: "blender",
        keywords: "smoothie shake kitchen",
        Icon: Blender,
      },
      {
        id: "salad",
        label: "salad",
        keywords: "greens vegetables healthy eat something green",
        Icon: Salad,
      },
      {
        id: "soup",
        label: "soup",
        keywords: "cook warm lunch broth",
        Icon: Soup,
      },
      {
        id: "sandwich",
        label: "sandwich",
        keywords: "lunch packed food",
        Icon: Sandwich,
      },
      {
        id: "hamburger",
        label: "burger",
        keywords: "takeaway dinner treat",
        Icon: Hamburger,
      },
      {
        id: "pizza",
        label: "pizza",
        keywords: "takeaway dinner treat",
        Icon: Pizza,
      },
      {
        id: "beef",
        label: "steak",
        keywords: "dinner protein meat cook",
        Icon: Beef,
      },
      {
        id: "drumstick",
        label: "chicken",
        keywords: "dinner protein roast",
        Icon: Drumstick,
      },
      {
        id: "fish",
        label: "fish",
        keywords: "dinner protein seafood omega",
        Icon: Fish,
      },
      {
        id: "shrimp",
        label: "prawns",
        keywords: "seafood dinner protein",
        Icon: Shrimp,
      },
      {
        id: "egg",
        label: "egg",
        keywords: "breakfast protein cook",
        Icon: Egg,
      },
      {
        id: "egg-fried",
        label: "fried egg",
        keywords: "breakfast cook brunch",
        Icon: EggFried,
      },
      {
        id: "carrot",
        label: "carrot",
        keywords: "vegetables veg eat greens",
        Icon: Carrot,
      },
      {
        id: "broccoli",
        label: "broccoli",
        keywords: "vegetables greens healthy",
        Icon: Broccoli,
      },
      {
        id: "bean",
        label: "beans",
        keywords: "protein pulses cook",
        Icon: Bean,
      },
      {
        id: "leafy-green",
        label: "greens",
        keywords: "salad vegetables healthy",
        Icon: LeafyGreen,
      },
      {
        id: "apple",
        label: "apple",
        keywords: "fruit snack healthy eat",
        Icon: Apple,
      },
      {
        id: "banana",
        label: "banana",
        keywords: "fruit snack potassium",
        Icon: Banana,
      },
      {
        id: "cherry",
        label: "cherry",
        keywords: "fruit snack sweet",
        Icon: Cherry,
      },
      {
        id: "grape",
        label: "grapes",
        keywords: "fruit snack vine",
        Icon: Grape,
      },
      {
        id: "citrus",
        label: "citrus",
        keywords: "orange lemon fruit vitamin",
        Icon: Citrus,
      },
      {
        id: "wheat",
        label: "wheat",
        keywords: "bread grain bake carbs",
        Icon: Wheat,
      },
      {
        id: "croissant",
        label: "croissant",
        keywords: "bake baking pastry breakfast",
        Icon: Croissant,
      },
      {
        id: "cake",
        label: "cake",
        keywords: "bake birthday treat",
        Icon: Cake,
      },
      {
        id: "cake-slice",
        label: "slice",
        keywords: "cake treat dessert",
        Icon: CakeSlice,
      },
      {
        id: "cookie",
        label: "cookie",
        keywords: "bake treat snack",
        Icon: Cookie,
      },
      {
        id: "donut",
        label: "doughnut",
        keywords: "treat sweet snack",
        Icon: Donut,
      },
      {
        id: "ice-cream-cone",
        label: "ice cream",
        keywords: "treat dessert sweet",
        Icon: IceCreamCone,
      },
      {
        id: "candy",
        label: "sweets",
        keywords: "treat sugar snack",
        Icon: Candy,
      },
      {
        id: "popsicle",
        label: "ice lolly",
        keywords: "treat summer sweet",
        Icon: Popsicle,
      },
      {
        id: "coffee",
        label: "coffee",
        keywords: "tea make tea morning brew drink",
        Icon: Coffee,
      },
      {
        id: "cup-soda",
        label: "soft drink",
        keywords: "fizzy cold drink",
        Icon: CupSoda,
      },
      {
        id: "glass-water",
        label: "water",
        keywords: "drink hydrate glass",
        Icon: GlassWater,
      },
      {
        id: "milk",
        label: "milk",
        keywords: "drink dairy breakfast",
        Icon: Milk,
      },
      {
        id: "wine",
        label: "wine",
        keywords: "drink evening alcohol",
        Icon: Wine,
      },
      {
        id: "beer",
        label: "beer",
        keywords: "drink pub evening",
        Icon: Beer,
      },
      {
        id: "martini",
        label: "cocktail",
        keywords: "drink evening bar",
        Icon: Martini,
      },
      {
        id: "bottle-wine",
        label: "bottle",
        keywords: "wine drink evening",
        Icon: BottleWine,
      },
      {
        id: "refrigerator",
        label: "fridge",
        keywords: "kitchen food shop groceries",
        Icon: Refrigerator,
      },
      {
        id: "microwave",
        label: "microwave",
        keywords: "kitchen cook reheat",
        Icon: Microwave,
      },
      {
        id: "shopping-cart",
        label: "food shop",
        keywords: "groceries food shopping",
        Icon: ShoppingCart,
      },
      {
        id: "shopping-basket",
        label: "basket",
        keywords: "groceries shop food",
        Icon: ShoppingBasket,
      },
      {
        id: "brush-cleaning",
        label: "sweep",
        keywords: "clean cleaning tidy sweep up",
        Icon: BrushCleaning,
      },
      {
        id: "washing-machine",
        label: "laundry",
        keywords: "wash clothes chores",
        Icon: WashingMachine,
      },
      {
        id: "boxes",
        label: "boxes",
        keywords: "tidy up declutter sort storage",
        Icon: Boxes,
      },
      {
        id: "recycle",
        label: "recycle",
        keywords: "bins rubbish waste chores",
        Icon: Recycle,
      },
      {
        id: "trash-2",
        label: "bins",
        keywords: "rubbish waste take out",
        Icon: Trash2,
      },
      {
        id: "lamp",
        label: "lamp",
        keywords: "home evening light",
        Icon: Lamp,
      },
      {
        id: "house",
        label: "house",
        keywords: "home chores diy",
        Icon: House,
      },
      {
        id: "door-open",
        label: "door",
        keywords: "leave home go out",
        Icon: DoorOpen,
      },
    ],
  },
  {
    id: "health-and-care",
    label: "Health and care",
    Tab: Stethoscope,
    icons: [
      {
        id: "stethoscope",
        label: "stethoscope",
        keywords: "checkup doctor appointment",
        Icon: Stethoscope,
      },
      {
        id: "heart-pulse",
        label: "heart rate",
        keywords: "cardio pulse blood pressure",
        Icon: HeartPulse,
      },
      {
        id: "heart-plus",
        label: "heart health",
        keywords: "checkup cardio care",
        Icon: HeartPlus,
      },
      {
        id: "pill",
        label: "medication",
        keywords: "vitamins supplements meds",
        Icon: Pill,
      },
      {
        id: "pill-bottle",
        label: "prescription",
        keywords: "meds refill pharmacy",
        Icon: PillBottle,
      },
      {
        id: "syringe",
        label: "injection",
        keywords: "vaccine jab bloods",
        Icon: Syringe,
      },
      {
        id: "thermometer",
        label: "thermometer",
        keywords: "temperature sick recovery",
        Icon: Thermometer,
      },
      {
        id: "thermometer-sun",
        label: "fever",
        keywords: "hot unwell temperature",
        Icon: ThermometerSun,
      },
      {
        id: "thermometer-snowflake",
        label: "chill",
        keywords: "cold unwell temperature",
        Icon: ThermometerSnowflake,
      },
      {
        id: "bandage",
        label: "plaster",
        keywords: "first aid wound care",
        Icon: Bandage,
      },
      {
        id: "briefcase-medical",
        label: "first aid",
        keywords: "kit medical emergency",
        Icon: BriefcaseMedical,
      },
      {
        id: "hospital",
        label: "hospital",
        keywords: "appointment ward clinic",
        Icon: Hospital,
      },
      {
        id: "ambulance",
        label: "ambulance",
        keywords: "emergency urgent care",
        Icon: Ambulance,
      },
      {
        id: "microscope",
        label: "lab",
        keywords: "tests bloods results",
        Icon: Microscope,
      },
      {
        id: "test-tubes",
        label: "tests",
        keywords: "bloods lab results",
        Icon: TestTubes,
      },
      {
        id: "flask-conical",
        label: "flask",
        keywords: "lab sample science",
        Icon: FlaskConical,
      },
      {
        id: "beaker",
        label: "beaker",
        keywords: "lab test sample",
        Icon: Beaker,
      },
      {
        id: "dna",
        label: "dna",
        keywords: "genetics screening health",
        Icon: Dna,
      },
      {
        id: "bone-fracture",
        label: "injury",
        keywords: "break recovery physio",
        Icon: BoneFracture,
      },
      {
        id: "scan",
        label: "scan",
        keywords: "check screening body",
        Icon: Scan,
      },
      {
        id: "scan-line",
        label: "screening",
        keywords: "check test scan",
        Icon: ScanLine,
      },
      {
        id: "scan-face",
        label: "skincare",
        keywords: "face routine skin",
        Icon: ScanFace,
      },
      {
        id: "scan-heart",
        label: "check in",
        keywords: "mood feelings notice",
        Icon: ScanHeart,
      },
      {
        id: "droplet",
        label: "hydrate",
        keywords: "water drink sweat",
        Icon: Droplet,
      },
      {
        id: "droplets",
        label: "water intake",
        keywords: "hydration glasses drink",
        Icon: Droplets,
      },
      {
        id: "toilet",
        label: "loo",
        keywords: "bathroom gut routine",
        Icon: Toilet,
      },
      {
        id: "soap-dispenser-droplet",
        label: "hand wash",
        keywords: "hygiene wash clean",
        Icon: SoapDispenserDroplet,
      },
      {
        id: "towel-rack",
        label: "towel",
        keywords: "bathroom wash routine",
        Icon: TowelRack,
      },
      {
        id: "bubbles",
        label: "bubbles",
        keywords: "bath wash clean",
        Icon: Bubbles,
      },
      {
        id: "shield-check",
        label: "protected",
        keywords: "cover immunity health",
        Icon: ShieldCheck,
      },
      {
        id: "shield-plus",
        label: "insurance",
        keywords: "cover health protect",
        Icon: ShieldPlus,
      },
      {
        id: "sun",
        label: "vitamin d",
        keywords: "sunlight daylight outside",
        Icon: Sun,
      },
      {
        id: "watch",
        label: "watch",
        keywords: "wearable track steps",
        Icon: Watch,
      },
      {
        id: "venus",
        label: "cycle",
        keywords: "period tracking women",
        Icon: Venus,
      },
      {
        id: "mars",
        label: "men's health",
        keywords: "checkup screening",
        Icon: Mars,
      },
      {
        id: "cigarette",
        label: "smoking",
        keywords: "habit cut down",
        Icon: Cigarette,
      },
      {
        id: "cigarette-off",
        label: "quit smoking",
        keywords: "smoke free stop",
        Icon: CigaretteOff,
      },
      {
        id: "wine-off",
        label: "alcohol free",
        keywords: "sober dry no drink",
        Icon: WineOff,
      },
      {
        id: "beer-off",
        label: "no beer",
        keywords: "sober dry alcohol free",
        Icon: BeerOff,
      },
      {
        id: "candy-off",
        label: "no sugar",
        keywords: "sweets cut back",
        Icon: CandyOff,
      },
      {
        id: "vegan",
        label: "vegan",
        keywords: "plant based diet",
        Icon: Vegan,
      },
      {
        id: "ban",
        label: "no",
        keywords: "stop avoid quit",
        Icon: Ban,
      },
      {
        id: "smile",
        label: "good day",
        keywords: "mood happy cheerful",
        Icon: Smile,
      },
      {
        id: "meh",
        label: "okay",
        keywords: "mood neutral fine",
        Icon: Meh,
      },
      {
        id: "frown",
        label: "low",
        keywords: "mood sad down",
        Icon: Frown,
      },
      {
        id: "laugh",
        label: "joy",
        keywords: "mood laughter happy",
        Icon: Laugh,
      },
      {
        id: "angry",
        label: "angry",
        keywords: "mood anger vent",
        Icon: Angry,
      },
      {
        id: "annoyed",
        label: "annoyed",
        keywords: "mood irritable frustrated",
        Icon: Annoyed,
      },
      {
        id: "hand",
        label: "hand",
        keywords: "wash grip stretch",
        Icon: Hand,
      },
      {
        id: "fingerprint-pattern",
        label: "daily log",
        keywords: "check in record habit",
        Icon: FingerprintPattern,
      },
      {
        id: "scale",
        label: "weigh in",
        keywords: "weight scales track",
        Icon: Scale,
      },
      {
        id: "percent",
        label: "percentage",
        keywords: "body fat track",
        Icon: Percent,
      },
      {
        id: "bug",
        label: "unwell",
        keywords: "bug sick illness",
        Icon: Bug,
      },
      {
        id: "life-buoy",
        label: "support",
        keywords: "help crisis reach out",
        Icon: LifeBuoy,
      },
    ],
  },
  {
    id: "people-and-outside",
    label: "People and outside",
    Tab: Users,
    icons: [
      {
        id: "users",
        label: "people",
        keywords: "friends saw friends coffee with a friend social",
        Icon: Users,
      },
      {
        id: "users-round",
        label: "group",
        keywords: "friends team social meet",
        Icon: UsersRound,
      },
      {
        id: "user-plus",
        label: "new friend",
        keywords: "meet introduce social",
        Icon: UserPlus,
      },
      {
        id: "user-round-check",
        label: "caught up",
        keywords: "friend met social",
        Icon: UserRoundCheck,
      },
      {
        id: "heart",
        label: "heart",
        keywords: "love date night partner",
        Icon: Heart,
      },
      {
        id: "heart-handshake",
        label: "care",
        keywords: "kindness support love",
        Icon: HeartHandshake,
      },
      {
        id: "handshake",
        label: "handshake",
        keywords: "meet colleague network deal",
        Icon: Handshake,
      },
      {
        id: "hand-heart",
        label: "give",
        keywords: "kindness volunteer care",
        Icon: HandHeart,
      },
      {
        id: "hand-helping",
        label: "help",
        keywords: "volunteer support lend a hand",
        Icon: HandHelping,
      },
      {
        id: "phone-call",
        label: "call",
        keywords: "call home ring phone",
        Icon: PhoneCall,
      },
      {
        id: "message-circle",
        label: "message",
        keywords: "text a friend chat dm",
        Icon: MessageCircle,
      },
      {
        id: "message-square",
        label: "chat",
        keywords: "text message talk",
        Icon: MessageSquare,
      },
      {
        id: "messages-square",
        label: "group chat",
        keywords: "friends chat threads",
        Icon: MessagesSquare,
      },
      {
        id: "video",
        label: "video call",
        keywords: "facetime zoom call",
        Icon: Video,
      },
      {
        id: "gift",
        label: "gift",
        keywords: "present birthday give",
        Icon: Gift,
      },
      {
        id: "party-popper",
        label: "party",
        keywords: "celebrate birthday night out",
        Icon: PartyPopper,
      },
      {
        id: "balloon",
        label: "balloon",
        keywords: "celebrate birthday party",
        Icon: Balloon,
      },
      {
        id: "baby",
        label: "baby",
        keywords: "kids family childcare",
        Icon: Baby,
      },
      {
        id: "dog",
        label: "dog",
        keywords: "walk the dog pet",
        Icon: Dog,
      },
      {
        id: "cat",
        label: "cat",
        keywords: "pet feed cuddle",
        Icon: Cat,
      },
      {
        id: "paw-print",
        label: "paw",
        keywords: "pet cat walk feed",
        Icon: PawPrint,
      },
      {
        id: "bird",
        label: "bird",
        keywords: "feed the birds nature watch",
        Icon: Bird,
      },
      {
        id: "squirrel",
        label: "squirrel",
        keywords: "nature watch park",
        Icon: Squirrel,
      },
      {
        id: "rabbit",
        label: "rabbit",
        keywords: "nature pet watch",
        Icon: Rabbit,
      },
      {
        id: "vote",
        label: "vote",
        keywords: "civic election community",
        Icon: Vote,
      },
      {
        id: "globe",
        label: "globe",
        keywords: "world travel abroad",
        Icon: Globe,
      },
      {
        id: "ferris-wheel",
        label: "day out",
        keywords: "fair funfair outing",
        Icon: FerrisWheel,
      },
      {
        id: "plane",
        label: "plane",
        keywords: "fly travel trip holiday",
        Icon: Plane,
      },
      {
        id: "plane-takeoff",
        label: "take off",
        keywords: "fly holiday trip",
        Icon: PlaneTakeoff,
      },
      {
        id: "car",
        label: "car",
        keywords: "drive commute trip",
        Icon: Car,
      },
      {
        id: "bus",
        label: "bus",
        keywords: "commute transit travel",
        Icon: Bus,
      },
      {
        id: "train-front",
        label: "train",
        keywords: "commute travel rail",
        Icon: TrainFront,
      },
      {
        id: "tram-front",
        label: "tram",
        keywords: "commute transit city",
        Icon: TramFront,
      },
      {
        id: "ship",
        label: "ship",
        keywords: "ferry sea travel",
        Icon: Ship,
      },
      {
        id: "luggage",
        label: "luggage",
        keywords: "pack trip travel holiday",
        Icon: Luggage,
      },
      {
        id: "map",
        label: "map",
        keywords: "plan trip explore route",
        Icon: MapIcon,
      },
      {
        id: "map-pin",
        label: "place",
        keywords: "location visit somewhere new",
        Icon: MapPin,
      },
      {
        id: "map-pinned",
        label: "pinned",
        keywords: "places visit explore",
        Icon: MapPinned,
      },
      {
        id: "signpost",
        label: "signpost",
        keywords: "walk directions route",
        Icon: Signpost,
      },
      {
        id: "ticket",
        label: "ticket",
        keywords: "show gig event booking",
        Icon: Ticket,
      },
      {
        id: "binoculars",
        label: "binoculars",
        keywords: "birdwatching spotting look",
        Icon: Binoculars,
      },
      {
        id: "tree-pine",
        label: "tree",
        keywords: "forest woods nature walk",
        Icon: TreePine,
      },
      {
        id: "tree-deciduous",
        label: "oak",
        keywords: "tree woods nature",
        Icon: TreeDeciduous,
      },
      {
        id: "tree-palm",
        label: "palm",
        keywords: "holiday beach warm",
        Icon: TreePalm,
      },
      {
        id: "trees",
        label: "woods",
        keywords: "forest nature outdoors",
        Icon: Trees,
      },
      {
        id: "shrub",
        label: "shrub",
        keywords: "garden nature green",
        Icon: Shrub,
      },
      {
        id: "leaf",
        label: "leaf",
        keywords: "nature outdoors autumn green",
        Icon: Leaf,
      },
      {
        id: "flower",
        label: "flower",
        keywords: "plants garden bloom",
        Icon: Flower,
      },
      {
        id: "rose",
        label: "rose",
        keywords: "garden flowers bloom",
        Icon: Rose,
      },
      {
        id: "sprout",
        label: "sprout",
        keywords: "water the plants garden grow seedling",
        Icon: Sprout,
      },
      {
        id: "sunset",
        label: "sunset",
        keywords: "evening outside golden hour",
        Icon: Sunset,
      },
      {
        id: "cloud-sun",
        label: "weather",
        keywords: "outside day forecast",
        Icon: CloudSun,
      },
      {
        id: "umbrella",
        label: "umbrella",
        keywords: "rain outside weather",
        Icon: Umbrella,
      },
      {
        id: "telescope",
        label: "telescope",
        keywords: "stars stargazing night sky",
        Icon: Telescope,
      },
    ],
  },
];

/**
 * Every icon by id, flattened once at module load.
 *
 * A `Map` rather than a plain object because the keys come from the database:
 * `mark` is free text a user can set, and `{}["constructor"]` is a function
 * while `new Map().get("constructor")` is `undefined`. The lookup below is the
 * one place stored data becomes a component, so it is the one place that has to
 * be uninteresting.
 */
const BY_ID: ReadonlyMap<string, MarkIcon> = new Map(
  ICON_GROUPS.flatMap((group) => group.icons).map((icon) => [icon.id, icon]),
);

/** Every icon in grid order — eight pages of fifty-four, one per tab. */
export const ALL_ICONS: readonly MarkIcon[] = ICON_GROUPS.flatMap(
  (group) => group.icons,
);

/** The stored form of an icon mark. The inverse of `iconFor`. */
export function iconMark(id: string) {
  return `${ICON_PREFIX}${id}`;
}

/**
 * The icon a mark names, or `null` if it names none.
 *
 * `null` is the ordinary answer for a letter or for one of the emoji already in
 * the database, and every caller has to draw those anyway. It is also the
 * answer for a mark that starts with `icon:` and doesn't match — an id that was
 * removed from the set above, say — which is why callers fall through to the
 * grapheme rather than rendering a placeholder. The worst case is a sticker
 * that shows the words it was stored as; the alternative was a blank circle.
 */
export function iconFor(mark: string): MarkIcon | null {
  if (!mark.startsWith(ICON_PREFIX)) return null;
  return BY_ID.get(mark.slice(ICON_PREFIX.length)) ?? null;
}

/**
 * Is this mark a valid icon name?
 *
 * Split out from `iconFor` for `validateDraft`, which needs the question
 * answered without touching a React component — `lib/stickers.ts` is unit
 * tested under `node --test`, where there is no bundler and no renderer.
 */
export function isIconMark(mark: string) {
  return iconFor(mark) !== null;
}
