// Regenerates `lib/emoji.ts` from the Unicode Consortium's own emoji-test.txt.
//
//   node scripts/build-emoji.mjs
//
// Run it when a new Unicode emoji version lands, and not otherwise. The output
// is checked in on purpose: the picker is a client component, so the list has to
// be in the bundle, and a build step that reaches out to unicode.org would put a
// network call between a clean checkout and a working app.
//
// What gets kept, and why:
//
// - `fully-qualified` only. The file lists three statuses, and the other two are
//   the same emoji written with the variation selector missing or misplaced.
//   Keeping them would show visible duplicates that render identically.
// - No `Component` group. That's skin tones and hair colours — modifiers, not
//   things you can put on a day by themselves.
// - No skin-tone variants (U+1F3FB..U+1F3FF). They multiply "person" emoji by
//   five and the neutral form is already in the list.

import { writeFile } from "node:fs/promises";

const SOURCE = "https://unicode.org/Public/emoji/latest/emoji-test.txt";

/**
 * The nine Unicode groups, folded into the eight tabs the picker shows.
 *
 * Smileys and people are one tab because Unicode's split between them is about
 * whether a body is involved, which is not a distinction anyone browsing for a
 * habit icon is making. The order is Unicode's own, which is also roughly the
 * order every emoji keyboard on every platform uses — worth matching, because
 * people navigate these by muscle memory rather than by reading the tabs.
 */
const TABS = [
  { id: "smileys", label: "Smileys & people", groups: ["Smileys & Emotion", "People & Body"] },
  { id: "nature", label: "Animals & nature", groups: ["Animals & Nature"] },
  { id: "food", label: "Food & drink", groups: ["Food & Drink"] },
  { id: "travel", label: "Travel & places", groups: ["Travel & Places"] },
  { id: "activities", label: "Activities", groups: ["Activities"] },
  { id: "objects", label: "Objects", groups: ["Objects"] },
  { id: "symbols", label: "Symbols", groups: ["Symbols"] },
  { id: "flags", label: "Flags", groups: ["Flags"] },
];

const SKIN_TONES = /1F3F[B-F]/;

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE} returned ${response.status}`);
const text = await response.text();

/** group name -> [{ emoji, name }] */
const byGroup = new Map();
let group = null;

for (const line of text.split("\n")) {
  const heading = line.match(/^# group: (.+)$/);
  if (heading) {
    group = heading[1].trim();
    continue;
  }
  if (line.startsWith("#") || line.trim() === "") continue;

  // 1F600 ; fully-qualified # 😀 E1.0 grinning face
  const row = line.match(/^([0-9A-F ]+?)\s*;\s*(\S+)\s*#\s*(\S+)\s+E\d+\.\d+\s+(.+)$/);
  if (!row) continue;

  const [, codepoints, status, emoji, name] = row;
  if (status !== "fully-qualified") continue;
  if (group === "Component") continue;
  if (SKIN_TONES.test(codepoints)) continue;

  if (!byGroup.has(group)) byGroup.set(group, []);
  byGroup.get(group).push({ emoji, name: name.trim() });
}

const tabs = TABS.map((tab) => ({
  id: tab.id,
  label: tab.label,
  emoji: tab.groups.flatMap((name) => {
    const rows = byGroup.get(name);
    if (!rows) throw new Error(`emoji-test.txt had no group called "${name}"`);
    return rows;
  }),
}));

const total = tabs.reduce((sum, tab) => sum + tab.emoji.length, 0);

const body = tabs
  .map((tab) => {
    const entries = tab.emoji
      .map(({ emoji, name }) => `    ["${emoji}", ${JSON.stringify(name)}],`)
      .join("\n");
    return `  {
    id: "${tab.id}",
    label: ${JSON.stringify(tab.label)},
    emoji: [
${entries}
    ],
  },`;
  })
  .join("\n");

const file = `// Generated by scripts/build-emoji.mjs — do not edit by hand.
//
// Source: ${SOURCE}
// ${total} emoji across ${tabs.length} tabs, fully-qualified only, no skin-tone
// variants. Re-run the script when a new Unicode emoji version lands.

/** One emoji and the name Unicode gives it, used for the tooltip and the label. */
export type EmojiEntry = readonly [emoji: string, name: string];

export type EmojiTab = {
  id: string;
  label: string;
  emoji: readonly EmojiEntry[];
};

export const EMOJI_TABS: readonly EmojiTab[] = [
${body}
];
`;

await writeFile(new URL("../lib/emoji.ts", import.meta.url), file);

console.log(`${total} emoji`);
for (const tab of tabs) console.log(`  ${tab.label}: ${tab.emoji.length}`);
